# TCL File Generated by Component Editor 18.1
# Mon Apr 29 21:23:31 PDT 2019
# DO NOT MODIFY


# 
# bilinear_interpolate_module "bilinear_interpolate_module" v1.0
#  2019.04.29.21:23:31
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module bilinear_interpolate_module
# 
set_module_property DESCRIPTION ""
set_module_property NAME bilinear_interpolate_module
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME bilinear_interpolate_module
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bilinear_interpolate_module
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bilinear_interpolate_module.sv SYSTEM_VERILOG PATH remap_v2/bilinear_interpolate_module.sv
add_fileset_file bilinear_interpolate_2pixels.sv SYSTEM_VERILOG PATH remap_v2/bilinear_interpolate_2pixels.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL bilinear_interpolate_module
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file bilinear_interpolate_module.sv SYSTEM_VERILOG PATH remap_v2/bilinear_interpolate_module.sv
add_fileset_file bilinear_interpolate_2pixels.sv SYSTEM_VERILOG PATH remap_v2/bilinear_interpolate_2pixels.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source dataBitsPerSymbol 17
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source pixel_out data Output 17
add_interface_port avalon_streaming_source pixel_out_valid valid Output 1


# 
# connection point pixel_conduit
# 
add_interface pixel_conduit conduit end
set_interface_property pixel_conduit associatedClock clock
set_interface_property pixel_conduit associatedReset ""
set_interface_property pixel_conduit ENABLED true
set_interface_property pixel_conduit EXPORT_OF ""
set_interface_property pixel_conduit PORT_NAME_MAP ""
set_interface_property pixel_conduit CMSIS_SVD_VARIABLES ""
set_interface_property pixel_conduit SVD_ADDRESS_GROUP ""

add_interface_port pixel_conduit pixel_in data Input 65
add_interface_port pixel_conduit pixel_in_valid valid Input 1
add_interface_port pixel_conduit fraction fraction Input 4


# 
# connection point avalon_streaming_source_1
# 
add_interface avalon_streaming_source_1 avalon_streaming start
set_interface_property avalon_streaming_source_1 associatedClock clock
set_interface_property avalon_streaming_source_1 dataBitsPerSymbol 8
set_interface_property avalon_streaming_source_1 errorDescriptor ""
set_interface_property avalon_streaming_source_1 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_1 maxChannel 0
set_interface_property avalon_streaming_source_1 readyLatency 0
set_interface_property avalon_streaming_source_1 ENABLED true
set_interface_property avalon_streaming_source_1 EXPORT_OF ""
set_interface_property avalon_streaming_source_1 PORT_NAME_MAP ""
set_interface_property avalon_streaming_source_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source_1 pixel_out_2 data Output 16
add_interface_port avalon_streaming_source_1 pixel_out_valid_2 valid Output 1

