# TCL File Generated by Component Editor 18.1
# Mon Apr 29 21:53:46 PDT 2019
# DO NOT MODIFY


# 
# cam_receiver "cam_receiver" v1.0
#  2019.04.29.21:53:46
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module cam_receiver
# 
set_module_property DESCRIPTION ""
set_module_property NAME cam_receiver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME cam_receiver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL camera_receiver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file camera_receiver.sv SYSTEM_VERILOG PATH camera_receiver.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL camera_receiver
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file camera_receiver.sv SYSTEM_VERILOG PATH camera_receiver.sv


# 
# parameters
# 
add_parameter frame_lines INTEGER 1540
set_parameter_property frame_lines DEFAULT_VALUE 1540
set_parameter_property frame_lines DISPLAY_NAME frame_lines
set_parameter_property frame_lines TYPE INTEGER
set_parameter_property frame_lines UNITS None
set_parameter_property frame_lines ALLOWED_RANGES -2147483648:2147483647
set_parameter_property frame_lines HDL_PARAMETER true
add_parameter frame_width INTEGER 2300
set_parameter_property frame_width DEFAULT_VALUE 2300
set_parameter_property frame_width DISPLAY_NAME frame_width
set_parameter_property frame_width TYPE INTEGER
set_parameter_property frame_width UNITS None
set_parameter_property frame_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property frame_width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink pclk clk Input 1


# 
# connection point sof_conduit
# 
add_interface sof_conduit conduit end
set_interface_property sof_conduit associatedClock clock_sink
set_interface_property sof_conduit associatedReset ""
set_interface_property sof_conduit ENABLED true
set_interface_property sof_conduit EXPORT_OF ""
set_interface_property sof_conduit PORT_NAME_MAP ""
set_interface_property sof_conduit CMSIS_SVD_VARIABLES ""
set_interface_property sof_conduit SVD_ADDRESS_GROUP ""

add_interface_port sof_conduit sof sof Output 1


# 
# connection point cam_in_conduit
# 
add_interface cam_in_conduit conduit end
set_interface_property cam_in_conduit associatedClock ""
set_interface_property cam_in_conduit associatedReset ""
set_interface_property cam_in_conduit ENABLED true
set_interface_property cam_in_conduit EXPORT_OF ""
set_interface_property cam_in_conduit PORT_NAME_MAP ""
set_interface_property cam_in_conduit CMSIS_SVD_VARIABLES ""
set_interface_property cam_in_conduit SVD_ADDRESS_GROUP ""

add_interface_port cam_in_conduit hs hs Input 1
add_interface_port cam_in_conduit vs vs Input 1
add_interface_port cam_in_conduit pixel_data pixel_data Input 10


# 
# connection point pixel_source
# 
add_interface pixel_source avalon_streaming start
set_interface_property pixel_source associatedClock clock_sink
set_interface_property pixel_source associatedReset reset
set_interface_property pixel_source dataBitsPerSymbol 10
set_interface_property pixel_source errorDescriptor ""
set_interface_property pixel_source firstSymbolInHighOrderBits true
set_interface_property pixel_source maxChannel 0
set_interface_property pixel_source readyLatency 0
set_interface_property pixel_source ENABLED true
set_interface_property pixel_source EXPORT_OF ""
set_interface_property pixel_source PORT_NAME_MAP ""
set_interface_property pixel_source CMSIS_SVD_VARIABLES ""
set_interface_property pixel_source SVD_ADDRESS_GROUP ""

add_interface_port pixel_source pixel_out data Output 10
add_interface_port pixel_source pixel_valid valid Output 1

