# TCL File Generated by Component Editor 18.1
# Sun Nov 15 13:23:18 PST 2020
# DO NOT MODIFY


# 
# coord_blk_reader "coord_blk_reader" v1.0
#  2020.11.15.13:23:18
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module coord_blk_reader
# 
set_module_property DESCRIPTION ""
set_module_property NAME coord_blk_reader
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME coord_blk_reader
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL coord_blk_reader
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file coord_blk_reader.sv SYSTEM_VERILOG PATH remap_v2/coord_blk_reader.sv TOP_LEVEL_FILE
add_fileset_file blk_request_fifo.v VERILOG PATH remap_v2/blk_request_fifo.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL coord_blk_reader
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file coord_blk_reader.sv SYSTEM_VERILOG PATH remap_v2/coord_blk_reader.sv
add_fileset_file blk_request_fifo.v VERILOG PATH remap_v2/blk_request_fifo.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits WORDS
set_interface_property avalon_master associatedClock ddr3_clk_sink
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master ddr3_address address Output 27
add_interface_port avalon_master ddr3_readdata readdata Input 256
add_interface_port avalon_master ddr3_read read Output 1
add_interface_port avalon_master ddr3_waitrequest waitrequest Input 1
add_interface_port avalon_master ddr3_readdatavalid readdatavalid Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock pclk_sink
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 16
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink blk_request_data data Input 16
add_interface_port avalon_streaming_sink blk_request_data_valid valid Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock ddr3_clk_sink
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 168
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source blk_out_data data Output 168
add_interface_port avalon_streaming_source blk_out_valid valid Output 1
add_interface_port avalon_streaming_source blk_out_ready ready Input 1


# 
# connection point ddr3_clk_sink
# 
add_interface ddr3_clk_sink clock end
set_interface_property ddr3_clk_sink clockRate 0
set_interface_property ddr3_clk_sink ENABLED true
set_interface_property ddr3_clk_sink EXPORT_OF ""
set_interface_property ddr3_clk_sink PORT_NAME_MAP ""
set_interface_property ddr3_clk_sink CMSIS_SVD_VARIABLES ""
set_interface_property ddr3_clk_sink SVD_ADDRESS_GROUP ""

add_interface_port ddr3_clk_sink ddr3_clk clk Input 1


# 
# connection point pclk_sink
# 
add_interface pclk_sink clock end
set_interface_property pclk_sink clockRate 0
set_interface_property pclk_sink ENABLED true
set_interface_property pclk_sink EXPORT_OF ""
set_interface_property pclk_sink PORT_NAME_MAP ""
set_interface_property pclk_sink CMSIS_SVD_VARIABLES ""
set_interface_property pclk_sink SVD_ADDRESS_GROUP ""

add_interface_port pclk_sink pclk clk Input 1


# 
# connection point remap_coords_base_address
# 
add_interface remap_coords_base_address conduit end
set_interface_property remap_coords_base_address associatedClock ddr3_clk_sink
set_interface_property remap_coords_base_address associatedReset ""
set_interface_property remap_coords_base_address ENABLED true
set_interface_property remap_coords_base_address EXPORT_OF ""
set_interface_property remap_coords_base_address PORT_NAME_MAP ""
set_interface_property remap_coords_base_address CMSIS_SVD_VARIABLES ""
set_interface_property remap_coords_base_address SVD_ADDRESS_GROUP ""

add_interface_port remap_coords_base_address base_address address Input 32

