# TCL File Generated by Component Editor 18.1
# Fri Mar 22 16:56:11 PDT 2019
# DO NOT MODIFY


# 
# DDR3_Writer_Simple "ddr3_writer_simple" v1.0
#  2019.03.22.16:56:11
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DDR3_Writer_Simple
# 
set_module_property DESCRIPTION ""
set_module_property NAME DDR3_Writer_Simple
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ddr3_writer_simple
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ddr3_pixel_writer_simple
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ddr3_pixel_writer_simple.sv SYSTEM_VERILOG PATH ddr3_pixel_writer_simple.sv TOP_LEVEL_FILE
add_fileset_file ddr3_writer_fifo.v VERILOG PATH ddr3_writer_fifo.v


# 
# parameters
# 
add_parameter in_width INTEGER 8
set_parameter_property in_width DEFAULT_VALUE 8
set_parameter_property in_width DISPLAY_NAME in_width
set_parameter_property in_width TYPE INTEGER
set_parameter_property in_width UNITS None
set_parameter_property in_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property in_width HDL_PARAMETER true
add_parameter burst_len INTEGER 8
set_parameter_property burst_len DEFAULT_VALUE 8
set_parameter_property burst_len DISPLAY_NAME burst_len
set_parameter_property burst_len TYPE INTEGER
set_parameter_property burst_len UNITS None
set_parameter_property burst_len ALLOWED_RANGES -2147483648:2147483647
set_parameter_property burst_len HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits WORDS
set_interface_property avalon_master associatedClock ddr3_clk_sink
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master ddr3_write_address address Output 27
add_interface_port avalon_master ddr3_write_data writedata Output 256
add_interface_port avalon_master ddr3_write write Output 1
add_interface_port avalon_master ddr3_waitrequest waitrequest Input 1
add_interface_port avalon_master ddr3_burstcount burstcount Output 4


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock pclk_sink
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end fifo_level fifo_level Output 9
add_interface_port conduit_end fifo_full_latch fifo_full_latch Output 1
add_interface_port conduit_end vs vsync Input 1
add_interface_port conduit_end pixel pixel Input in_width
add_interface_port conduit_end hs hsync Input 1


# 
# connection point ddr3_clk_sink
# 
add_interface ddr3_clk_sink clock end
set_interface_property ddr3_clk_sink clockRate 0
set_interface_property ddr3_clk_sink ENABLED true
set_interface_property ddr3_clk_sink EXPORT_OF ""
set_interface_property ddr3_clk_sink PORT_NAME_MAP ""
set_interface_property ddr3_clk_sink CMSIS_SVD_VARIABLES ""
set_interface_property ddr3_clk_sink SVD_ADDRESS_GROUP ""

add_interface_port ddr3_clk_sink ddr3_clk clk Input 1


# 
# connection point pclk_sink
# 
add_interface pclk_sink clock end
set_interface_property pclk_sink clockRate 0
set_interface_property pclk_sink ENABLED true
set_interface_property pclk_sink EXPORT_OF ""
set_interface_property pclk_sink PORT_NAME_MAP ""
set_interface_property pclk_sink CMSIS_SVD_VARIABLES ""
set_interface_property pclk_sink SVD_ADDRESS_GROUP ""

add_interface_port pclk_sink pclk clk Input 1

