# TCL File Generated by Component Editor 18.1
# Mon Apr 29 21:54:03 PDT 2019
# DO NOT MODIFY


# 
# debayer "debayer" v1.0
#  2019.04.29.21:54:03
# Output line length is (line_length - 4) pixels
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module debayer
# 
set_module_property DESCRIPTION "Output line length is (line_length - 4) pixels"
set_module_property NAME debayer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME debayer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL debayer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file debayer.sv SYSTEM_VERILOG PATH debayer.sv TOP_LEVEL_FILE
add_fileset_file line_buf.v VERILOG PATH line_buf.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL debayer
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file debayer.sv SYSTEM_VERILOG PATH debayer.sv
add_fileset_file line_buf.v VERILOG PATH line_buf.v


# 
# parameters
# 
add_parameter line_length INTEGER 2304
set_parameter_property line_length DEFAULT_VALUE 2304
set_parameter_property line_length DISPLAY_NAME line_length
set_parameter_property line_length TYPE INTEGER
set_parameter_property line_length UNITS None
set_parameter_property line_length ALLOWED_RANGES -2147483648:2147483647
set_parameter_property line_length HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point sof_in_conduit
# 
add_interface sof_in_conduit conduit end
set_interface_property sof_in_conduit associatedClock clock
set_interface_property sof_in_conduit associatedReset ""
set_interface_property sof_in_conduit ENABLED true
set_interface_property sof_in_conduit EXPORT_OF ""
set_interface_property sof_in_conduit PORT_NAME_MAP ""
set_interface_property sof_in_conduit CMSIS_SVD_VARIABLES ""
set_interface_property sof_in_conduit SVD_ADDRESS_GROUP ""

add_interface_port sof_in_conduit sof_in sof Input 1


# 
# connection point pixel_in_sink
# 
add_interface pixel_in_sink avalon_streaming end
set_interface_property pixel_in_sink associatedClock clock
set_interface_property pixel_in_sink associatedReset reset
set_interface_property pixel_in_sink dataBitsPerSymbol 10
set_interface_property pixel_in_sink errorDescriptor ""
set_interface_property pixel_in_sink firstSymbolInHighOrderBits true
set_interface_property pixel_in_sink maxChannel 0
set_interface_property pixel_in_sink readyLatency 0
set_interface_property pixel_in_sink ENABLED true
set_interface_property pixel_in_sink EXPORT_OF ""
set_interface_property pixel_in_sink PORT_NAME_MAP ""
set_interface_property pixel_in_sink CMSIS_SVD_VARIABLES ""
set_interface_property pixel_in_sink SVD_ADDRESS_GROUP ""

add_interface_port pixel_in_sink pixel_data data Input 10
add_interface_port pixel_in_sink pixel_data_valid valid Input 1


# 
# connection point rgb_pixel_source
# 
add_interface rgb_pixel_source avalon_streaming start
set_interface_property rgb_pixel_source associatedClock clock
set_interface_property rgb_pixel_source associatedReset reset
set_interface_property rgb_pixel_source dataBitsPerSymbol 16
set_interface_property rgb_pixel_source errorDescriptor ""
set_interface_property rgb_pixel_source firstSymbolInHighOrderBits true
set_interface_property rgb_pixel_source maxChannel 0
set_interface_property rgb_pixel_source readyLatency 0
set_interface_property rgb_pixel_source ENABLED true
set_interface_property rgb_pixel_source EXPORT_OF ""
set_interface_property rgb_pixel_source PORT_NAME_MAP ""
set_interface_property rgb_pixel_source CMSIS_SVD_VARIABLES ""
set_interface_property rgb_pixel_source SVD_ADDRESS_GROUP ""

add_interface_port rgb_pixel_source pixel_out_data data Output 16
add_interface_port rgb_pixel_source pixel_out_data_valid valid Output 1


# 
# connection point sof_out_0
# 
add_interface sof_out_0 avalon_streaming start
set_interface_property sof_out_0 associatedClock clock
set_interface_property sof_out_0 associatedReset reset
set_interface_property sof_out_0 dataBitsPerSymbol 1
set_interface_property sof_out_0 errorDescriptor ""
set_interface_property sof_out_0 firstSymbolInHighOrderBits true
set_interface_property sof_out_0 maxChannel 0
set_interface_property sof_out_0 readyLatency 0
set_interface_property sof_out_0 ENABLED true
set_interface_property sof_out_0 EXPORT_OF ""
set_interface_property sof_out_0 PORT_NAME_MAP ""
set_interface_property sof_out_0 CMSIS_SVD_VARIABLES ""
set_interface_property sof_out_0 SVD_ADDRESS_GROUP ""

add_interface_port sof_out_0 sof data Output 1


# 
# connection point sof_out_1
# 
add_interface sof_out_1 avalon_streaming start
set_interface_property sof_out_1 associatedClock clock
set_interface_property sof_out_1 associatedReset reset
set_interface_property sof_out_1 dataBitsPerSymbol 1
set_interface_property sof_out_1 errorDescriptor ""
set_interface_property sof_out_1 firstSymbolInHighOrderBits true
set_interface_property sof_out_1 maxChannel 0
set_interface_property sof_out_1 readyLatency 0
set_interface_property sof_out_1 ENABLED true
set_interface_property sof_out_1 EXPORT_OF ""
set_interface_property sof_out_1 PORT_NAME_MAP ""
set_interface_property sof_out_1 CMSIS_SVD_VARIABLES ""
set_interface_property sof_out_1 SVD_ADDRESS_GROUP ""

add_interface_port sof_out_1 sof_2 data Output 1

