# TCL File Generated by Component Editor 18.1
# Sat May 25 16:27:36 PDT 2019
# DO NOT MODIFY


# 
# gray_downsample "gray_downsample" v1.0
#  2019.05.25.16:27:36
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module gray_downsample
# 
set_module_property DESCRIPTION ""
set_module_property NAME gray_downsample
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME gray_downsample
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gray_downsample
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gray_downsample.sv SYSTEM_VERILOG PATH remap_v2/grayscale/gray_downsample.sv TOP_LEVEL_FILE
add_fileset_file gray_horiz_downsample.sv SYSTEM_VERILOG PATH remap_v2/grayscale/gray_horiz_downsample.sv
add_fileset_file grayscale_remap_ram.v VERILOG PATH remap_v2/grayscale/grayscale_remap_ram.v
add_fileset_file gray_remap_coord_fifo.v VERILOG PATH remap_v2/grayscale/gray_remap_coord_fifo.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL gray_downsample
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file gray_downsample.sv SYSTEM_VERILOG PATH remap_v2/grayscale/gray_downsample.sv
add_fileset_file gray_horiz_downsample.sv SYSTEM_VERILOG PATH remap_v2/grayscale/gray_horiz_downsample.sv
add_fileset_file grayscale_remap_ram.v VERILOG PATH remap_v2/grayscale/grayscale_remap_ram.v
add_fileset_file gray_remap_coord_fifo.v VERILOG PATH remap_v2/grayscale/gray_remap_coord_fifo.v


# 
# parameters
# 
add_parameter wr_blk_w INTEGER 32
set_parameter_property wr_blk_w DEFAULT_VALUE 32
set_parameter_property wr_blk_w DISPLAY_NAME wr_blk_w
set_parameter_property wr_blk_w TYPE INTEGER
set_parameter_property wr_blk_w UNITS None
set_parameter_property wr_blk_w ALLOWED_RANGES -2147483648:2147483647
set_parameter_property wr_blk_w HDL_PARAMETER true
add_parameter wr_frame_w INTEGER 2048
set_parameter_property wr_frame_w DEFAULT_VALUE 2048
set_parameter_property wr_frame_w DISPLAY_NAME wr_frame_w
set_parameter_property wr_frame_w TYPE INTEGER
set_parameter_property wr_frame_w UNITS None
set_parameter_property wr_frame_w ALLOWED_RANGES -2147483648:2147483647
set_parameter_property wr_frame_w HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point coord_sink
# 
add_interface coord_sink avalon_streaming end
set_interface_property coord_sink associatedClock clock
set_interface_property coord_sink associatedReset reset
set_interface_property coord_sink dataBitsPerSymbol 34
set_interface_property coord_sink errorDescriptor ""
set_interface_property coord_sink firstSymbolInHighOrderBits true
set_interface_property coord_sink maxChannel 0
set_interface_property coord_sink readyLatency 0
set_interface_property coord_sink ENABLED true
set_interface_property coord_sink EXPORT_OF ""
set_interface_property coord_sink PORT_NAME_MAP ""
set_interface_property coord_sink CMSIS_SVD_VARIABLES ""
set_interface_property coord_sink SVD_ADDRESS_GROUP ""

add_interface_port coord_sink coords_in data Input 34
add_interface_port coord_sink coords_in_valid valid Input 1


# 
# connection point pixel_source
# 
add_interface pixel_source avalon_streaming start
set_interface_property pixel_source associatedClock clock
set_interface_property pixel_source associatedReset reset
set_interface_property pixel_source dataBitsPerSymbol 8
set_interface_property pixel_source errorDescriptor ""
set_interface_property pixel_source firstSymbolInHighOrderBits true
set_interface_property pixel_source maxChannel 0
set_interface_property pixel_source readyLatency 0
set_interface_property pixel_source ENABLED true
set_interface_property pixel_source EXPORT_OF ""
set_interface_property pixel_source PORT_NAME_MAP ""
set_interface_property pixel_source CMSIS_SVD_VARIABLES ""
set_interface_property pixel_source SVD_ADDRESS_GROUP ""

add_interface_port pixel_source pixel_out data Output 8
add_interface_port pixel_source pixel_out_valid valid Output 1


# 
# connection point coord_source
# 
add_interface coord_source avalon_streaming start
set_interface_property coord_source associatedClock clock
set_interface_property coord_source associatedReset reset
set_interface_property coord_source dataBitsPerSymbol 34
set_interface_property coord_source errorDescriptor ""
set_interface_property coord_source firstSymbolInHighOrderBits true
set_interface_property coord_source maxChannel 0
set_interface_property coord_source readyLatency 0
set_interface_property coord_source ENABLED true
set_interface_property coord_source EXPORT_OF ""
set_interface_property coord_source PORT_NAME_MAP ""
set_interface_property coord_source CMSIS_SVD_VARIABLES ""
set_interface_property coord_source SVD_ADDRESS_GROUP ""

add_interface_port coord_source coords_out data Output 34
add_interface_port coord_source coords_out_valid valid Output 1


# 
# connection point pixel_sink
# 
add_interface pixel_sink avalon_streaming end
set_interface_property pixel_sink associatedClock clock
set_interface_property pixel_sink associatedReset reset
set_interface_property pixel_sink dataBitsPerSymbol 8
set_interface_property pixel_sink errorDescriptor ""
set_interface_property pixel_sink firstSymbolInHighOrderBits true
set_interface_property pixel_sink maxChannel 0
set_interface_property pixel_sink readyLatency 0
set_interface_property pixel_sink ENABLED true
set_interface_property pixel_sink EXPORT_OF ""
set_interface_property pixel_sink PORT_NAME_MAP ""
set_interface_property pixel_sink CMSIS_SVD_VARIABLES ""
set_interface_property pixel_sink SVD_ADDRESS_GROUP ""

add_interface_port pixel_sink pixel_in data Input 8
add_interface_port pixel_sink pixel_in_valid valid Input 1

