# TCL File Generated by Component Editor 18.1
# Sun May 19 20:04:41 PDT 2019
# DO NOT MODIFY


# 
# rbcc_v2 "rbcc_v2" v1.0
#  2019.05.19.20:04:41
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module rbcc_v2
# 
set_module_property DESCRIPTION ""
set_module_property NAME rbcc_v2
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME rbcc_v2
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL rect_buffer_coord_calc_v2
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file rect_buffer_coord_calc_v2.sv SYSTEM_VERILOG PATH remap_v2/rect_buffer_coord_calc_v2.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL rect_buffer_coord_calc_v2
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file rect_buffer_coord_calc_v2.sv SYSTEM_VERILOG PATH remap_v2/rect_buffer_coord_calc_v2.sv


# 
# parameters
# 
add_parameter wr_blk_w INTEGER 32
set_parameter_property wr_blk_w DEFAULT_VALUE 32
set_parameter_property wr_blk_w DISPLAY_NAME wr_blk_w
set_parameter_property wr_blk_w TYPE INTEGER
set_parameter_property wr_blk_w UNITS None
set_parameter_property wr_blk_w ALLOWED_RANGES -2147483648:2147483647
set_parameter_property wr_blk_w HDL_PARAMETER true
add_parameter wr_blk_h INTEGER 32
set_parameter_property wr_blk_h DEFAULT_VALUE 32
set_parameter_property wr_blk_h DISPLAY_NAME wr_blk_h
set_parameter_property wr_blk_h TYPE INTEGER
set_parameter_property wr_blk_h UNITS None
set_parameter_property wr_blk_h ALLOWED_RANGES -2147483648:2147483647
set_parameter_property wr_blk_h HDL_PARAMETER true
add_parameter coord_frac_bits INTEGER 2
set_parameter_property coord_frac_bits DEFAULT_VALUE 2
set_parameter_property coord_frac_bits DISPLAY_NAME coord_frac_bits
set_parameter_property coord_frac_bits TYPE INTEGER
set_parameter_property coord_frac_bits ENABLED false
set_parameter_property coord_frac_bits UNITS None
set_parameter_property coord_frac_bits ALLOWED_RANGES -2147483648:2147483647
set_parameter_property coord_frac_bits HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock_sink
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 66
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink coords_in data Input 66
add_interface_port avalon_streaming_sink coords_in_ready ready Output 1
add_interface_port avalon_streaming_sink coords_in_valid valid Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock_sink
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 33
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source coords_out data Output 33
add_interface_port avalon_streaming_source coords_out_valid valid Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink st_clk clk Input 1


# 
# connection point fifo_almost_full_conduit
# 
add_interface fifo_almost_full_conduit avalon_streaming end
set_interface_property fifo_almost_full_conduit associatedClock clock_sink
set_interface_property fifo_almost_full_conduit associatedReset reset
set_interface_property fifo_almost_full_conduit dataBitsPerSymbol 1
set_interface_property fifo_almost_full_conduit errorDescriptor ""
set_interface_property fifo_almost_full_conduit firstSymbolInHighOrderBits true
set_interface_property fifo_almost_full_conduit maxChannel 0
set_interface_property fifo_almost_full_conduit readyLatency 0
set_interface_property fifo_almost_full_conduit ENABLED true
set_interface_property fifo_almost_full_conduit EXPORT_OF ""
set_interface_property fifo_almost_full_conduit PORT_NAME_MAP ""
set_interface_property fifo_almost_full_conduit CMSIS_SVD_VARIABLES ""
set_interface_property fifo_almost_full_conduit SVD_ADDRESS_GROUP ""

add_interface_port fifo_almost_full_conduit writer_fifo_almost_full data Input 1

