# TCL File Generated by Component Editor 18.1
# Sun Mar 24 17:27:47 PDT 2019
# DO NOT MODIFY


# 
# rect_buffer_module "rect_buffer_module" v1.0
#  2019.03.24.17:27:47
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module rect_buffer_module
# 
set_module_property DESCRIPTION ""
set_module_property NAME rect_buffer_module
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME rect_buffer_module
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL rect_buffer_module
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file rect_buffer_module.sv SYSTEM_VERILOG PATH remap_v2/rect_buffer_module.sv TOP_LEVEL_FILE
add_fileset_file remap_buffer.v VERILOG PATH remap_v2/remap_buffer.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL rect_buffer_module
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file rect_buffer_module.sv SYSTEM_VERILOG PATH remap_v2/rect_buffer_module.sv
add_fileset_file remap_buffer.v VERILOG PATH remap_v2/remap_buffer.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point read
# 
add_interface read conduit end
set_interface_property read associatedClock clock
set_interface_property read associatedReset ""
set_interface_property read ENABLED true
set_interface_property read EXPORT_OF ""
set_interface_property read PORT_NAME_MAP ""
set_interface_property read CMSIS_SVD_VARIABLES ""
set_interface_property read SVD_ADDRESS_GROUP ""

add_interface_port read read_address address Input 60
add_interface_port read read_readdata data Output 64


# 
# connection point write
# 
add_interface write conduit end
set_interface_property write associatedClock clock
set_interface_property write associatedReset ""
set_interface_property write ENABLED true
set_interface_property write EXPORT_OF ""
set_interface_property write PORT_NAME_MAP ""
set_interface_property write CMSIS_SVD_VARIABLES ""
set_interface_property write SVD_ADDRESS_GROUP ""

add_interface_port write write_address address Input 60
add_interface_port write write_writedata data Input 64
add_interface_port write write_write write Input 4

