# TCL File Generated by Component Editor 18.1
# Sun May 19 20:05:32 PDT 2019
# DO NOT MODIFY


# 
# rect_buffer_reader_v2 "rect_buffer_reader_v2" v1.0
#  2019.05.19.20:05:32
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module rect_buffer_reader_v2
# 
set_module_property DESCRIPTION ""
set_module_property NAME rect_buffer_reader_v2
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME rect_buffer_reader_v2
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL rect_buffer_reader
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file rect_buffer_reader_v2.sv SYSTEM_VERILOG PATH remap_v2/rect_buffer_reader_v2.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL rect_buffer_reader
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file rect_buffer_reader_v2.sv SYSTEM_VERILOG PATH remap_v2/rect_buffer_reader_v2.sv


# 
# parameters
# 
add_parameter buffer_w INTEGER 2048
set_parameter_property buffer_w DEFAULT_VALUE 2048
set_parameter_property buffer_w DISPLAY_NAME buffer_w
set_parameter_property buffer_w TYPE INTEGER
set_parameter_property buffer_w UNITS None
set_parameter_property buffer_w ALLOWED_RANGES -2147483648:2147483647
set_parameter_property buffer_w HDL_PARAMETER true
add_parameter buffer_h INTEGER 32
set_parameter_property buffer_h DEFAULT_VALUE 32
set_parameter_property buffer_h DISPLAY_NAME buffer_h
set_parameter_property buffer_h TYPE INTEGER
set_parameter_property buffer_h UNITS None
set_parameter_property buffer_h ALLOWED_RANGES -2147483648:2147483647
set_parameter_property buffer_h HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point buf
# 
add_interface buf clock end
set_interface_property buf clockRate 0
set_interface_property buf ENABLED true
set_interface_property buf EXPORT_OF ""
set_interface_property buf PORT_NAME_MAP ""
set_interface_property buf CMSIS_SVD_VARIABLES ""
set_interface_property buf SVD_ADDRESS_GROUP ""

add_interface_port buf buf_read_clk clk Input 1


# 
# connection point read_conduit
# 
add_interface read_conduit conduit end
set_interface_property read_conduit associatedClock buf
set_interface_property read_conduit associatedReset ""
set_interface_property read_conduit ENABLED true
set_interface_property read_conduit EXPORT_OF ""
set_interface_property read_conduit PORT_NAME_MAP ""
set_interface_property read_conduit CMSIS_SVD_VARIABLES ""
set_interface_property read_conduit SVD_ADDRESS_GROUP ""

add_interface_port read_conduit buf_data data Input 64
add_interface_port read_conduit buf_address address Output 60


# 
# connection point pixel_stream_conduit
# 
add_interface pixel_stream_conduit conduit end
set_interface_property pixel_stream_conduit associatedClock buf
set_interface_property pixel_stream_conduit associatedReset ""
set_interface_property pixel_stream_conduit ENABLED true
set_interface_property pixel_stream_conduit EXPORT_OF ""
set_interface_property pixel_stream_conduit PORT_NAME_MAP ""
set_interface_property pixel_stream_conduit CMSIS_SVD_VARIABLES ""
set_interface_property pixel_stream_conduit SVD_ADDRESS_GROUP ""

add_interface_port pixel_stream_conduit pix_to_inter data Output 65
add_interface_port pixel_stream_conduit pix_to_inter_valid valid Output 1
add_interface_port pixel_stream_conduit read_coord_frac_to_inter fraction Output 4


# 
# connection point read_coord_sink
# 
add_interface read_coord_sink avalon_streaming end
set_interface_property read_coord_sink associatedClock buf
set_interface_property read_coord_sink associatedReset reset
set_interface_property read_coord_sink dataBitsPerSymbol 33
set_interface_property read_coord_sink errorDescriptor ""
set_interface_property read_coord_sink firstSymbolInHighOrderBits true
set_interface_property read_coord_sink maxChannel 0
set_interface_property read_coord_sink readyLatency 0
set_interface_property read_coord_sink ENABLED true
set_interface_property read_coord_sink EXPORT_OF ""
set_interface_property read_coord_sink PORT_NAME_MAP ""
set_interface_property read_coord_sink CMSIS_SVD_VARIABLES ""
set_interface_property read_coord_sink SVD_ADDRESS_GROUP ""

add_interface_port read_coord_sink read_coord_in data Input 33
add_interface_port read_coord_sink read_coord_valid valid Input 1

