# TCL File Generated by Component Editor 18.1
# Mon Apr 22 16:37:25 PDT 2019
# DO NOT MODIFY


# 
# rect_buffer_writer_v2 "rect_buffer_writer_v2" v1.0
#  2019.04.22.16:37:25
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module rect_buffer_writer_v2
# 
set_module_property DESCRIPTION ""
set_module_property NAME rect_buffer_writer_v2
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME rect_buffer_writer_v2
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL rect_buffer_writer_v2
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file rect_buffer_writer_v2.sv SYSTEM_VERILOG PATH remap_v2/rect_buffer_writer_v2.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL rect_buffer_writer_v2
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file rect_buffer_writer_v2.sv SYSTEM_VERILOG PATH remap_v2/rect_buffer_writer_v2.sv


# 
# parameters
# 
add_parameter buffer_w INTEGER 2048
set_parameter_property buffer_w DEFAULT_VALUE 2048
set_parameter_property buffer_w DISPLAY_NAME buffer_w
set_parameter_property buffer_w TYPE INTEGER
set_parameter_property buffer_w UNITS None
set_parameter_property buffer_w HDL_PARAMETER true
add_parameter buffer_h INTEGER 32
set_parameter_property buffer_h DEFAULT_VALUE 32
set_parameter_property buffer_h DISPLAY_NAME buffer_h
set_parameter_property buffer_h TYPE INTEGER
set_parameter_property buffer_h UNITS None
set_parameter_property buffer_h HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock_sink
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 16
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink st_data data Input 16
add_interface_port avalon_streaming_sink st_data_valid valid Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink st_clk clk Input 1


# 
# connection point write_conduit
# 
add_interface write_conduit conduit end
set_interface_property write_conduit associatedClock clock_sink
set_interface_property write_conduit associatedReset ""
set_interface_property write_conduit ENABLED true
set_interface_property write_conduit EXPORT_OF ""
set_interface_property write_conduit PORT_NAME_MAP ""
set_interface_property write_conduit CMSIS_SVD_VARIABLES ""
set_interface_property write_conduit SVD_ADDRESS_GROUP ""

add_interface_port write_conduit buf_data data Output 64
add_interface_port write_conduit buf_address address Output 60
add_interface_port write_conduit buf_write write Output 4


# 
# connection point buffer_row_conduit
# 
add_interface buffer_row_conduit conduit end
set_interface_property buffer_row_conduit associatedClock clock_sink
set_interface_property buffer_row_conduit associatedReset ""
set_interface_property buffer_row_conduit ENABLED true
set_interface_property buffer_row_conduit EXPORT_OF ""
set_interface_property buffer_row_conduit PORT_NAME_MAP ""
set_interface_property buffer_row_conduit CMSIS_SVD_VARIABLES ""
set_interface_property buffer_row_conduit SVD_ADDRESS_GROUP ""

add_interface_port buffer_row_conduit buf_row buffer_row Output 16


# 
# connection point frame_start_conduit
# 
add_interface frame_start_conduit avalon_streaming end
set_interface_property frame_start_conduit associatedClock clock_sink
set_interface_property frame_start_conduit associatedReset reset
set_interface_property frame_start_conduit dataBitsPerSymbol 1
set_interface_property frame_start_conduit errorDescriptor ""
set_interface_property frame_start_conduit firstSymbolInHighOrderBits true
set_interface_property frame_start_conduit maxChannel 0
set_interface_property frame_start_conduit readyLatency 0
set_interface_property frame_start_conduit ENABLED true
set_interface_property frame_start_conduit EXPORT_OF ""
set_interface_property frame_start_conduit PORT_NAME_MAP ""
set_interface_property frame_start_conduit CMSIS_SVD_VARIABLES ""
set_interface_property frame_start_conduit SVD_ADDRESS_GROUP ""

add_interface_port frame_start_conduit frame_start data Input 1

